# for more enhancement https://circleci.com/blog/six-optimization-tips-for-your-config/

version: 2.1

orbs:
  node: circleci/node@4.1.0

commands:
  install:
    description: "command for dependencies Installation"
    steps:
      # Download and cache dependencies
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package.json checksum
            # when this file is changed, this key will fail
            - v1-dependencies-{{ checksum "package.json" }}
            # Find the most recently generated cache used from any branch
            # - v1-dependencies-
      - run: 
          name: Install Client Dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - node/install-yarn
      - checkout
      - install
      - run:
          name: Build project
          command: yarn build

  test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - node/install-yarn
      - checkout
      - install
      - run: 
          name: Test
          command: yarn test

  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - node/install-yarn
      - checkout
      - install
      - run:
          name: Deploy at netlify
          command: yarn deploy

workflows:
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
